### PR TITLE
fix: hide overlay scrollbar using overflow-hidden

### LINKED ISSUE #165: Overlay window size Glitch
Hi, I have this behavior with the window overlay. Im not sure why. (check the bottom of the screenshot)

Image

Best !

### PR DESCRIPTION
**Pull request by buffalodebile**
Scrollbar was showing up on Windows on the overlay window. After Kieirra's feedback, went with a different approach: instead of touching the height, just rely on `overflow-hidden` that was already on the container to prevent the scrollbar from appearing. Reverted `h-screen` back to the original `h-7.5`.

## Description

The overlay had a visible scrollbar on Windows due to a height mismatch. Rather than changing the height (which was fragile), the fix keeps `h-7.5` and lets the existing `overflow-hidden` on the container handle it — anything that overflows stays hidden, no scrollbar.

Closes #165.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Enhancement of an existing feature
- [ ] Refactor / code cleanup
- [ ] Documentation
- [ ] Other: 

## Tested on

- [x] Windows
- [ ] Linux
- [ ] macOS

## Checklist

- [x] I have read [CONTRIBUTING.md](../CONTRIBUTING.md) and [GUIDELINES.md](../GUIDELINES.md)
- [x] My PR addresses **one single concern**
- [x] I tested my changes manually and they work as expected
- [x] I ran `cargo clippy` and `cargo fmt` (if Rust changes)
- [x] I checked for SonarQube issues on the draft PR

### CODE REVIEW

File: src/overlay/overlay.tsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ export const Overlay = () => {
         <div
             className={clsx(
                 'w-20',
-                'h-7.5',
+                'h-screen',
```
Comment (Kieirra) [inline src/overlay/overlay.tsx]: - Good point: your change is minimalist, which is exactly what we want for an open source PR.

- That said, `h-screen` isn't the right fix here, even if it appears to work, let me explain why. 
`h-screen` means "take the full height of the user's screen." 
It only works in this specific case because I currently constrain the overlay size from the Rust side, but that overlay height will change in the near future, which will immediately break your fix.

This is exactly what I described in https://github.com/Kieirra/murmure/issues/165#issuecomment-3939236202, a change seems to work in your current configuration but remain fragile and break in a different setup or after a future update.

Could you try a more robust approach, without touching the overlay size? The right fix here is probably `overflow-hidden` on the container, it hides anything that overflows outside the overlay bounds, so a scrollbar will never appear to reveal it, regardless of the overlay's height.

Tell me if it works.

**Review by Kieirra — CHANGES_REQUESTED** [review]
Thank you for opening this PR and for following the template, keeping changes minimalist is exactly the right approach.

I've left a comment directly on the relevant line explaining why `h-screen` isn't the right fix here and suggesting a more robust alternative. 

Feel free to update the PR with the new approach, I'll be happy to review it again

File: src/overlay/overlay.tsx (hunk 1 above)
Comment (buffalodebile) [reply src/overlay/overlay.tsx]: Makes sense, good catch. Reverted to `h-7.5` and kept `overflow-hidden` on the container tested on Windows and the scrollbar is gone. Let me know if it looks good!

**Comment by Kieirra** [comment]
If you’ve tested it and it fixes the issue, great 👍

I’ll test it as well to make sure there’s no regression on my side. I didn’t have the bug originally, so my testing will be a bit blind.

However, don’t forget to push your changes, the revert has been pushed, but the overflow-hidden update hasn’t.

File: src/overlay/overlay.tsx (hunk 1 above)
Comment (Kieirra) [reply src/overlay/overlay.tsx]: see https://github.com/Kieirra/murmure/pull/169#issuecomment-3939358288

**Comment by buffalodebile** [comment]
Pushed! Added `overflow: hidden` so the scrollbar is hidden at the webview level too. Its my first PR so Im not really use to this. Let me know if I forgot something.
